# Generated by Django 4.1.3 on 2022-12-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_uuidtaggeditem_alter_cheatsheet_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatsheet',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='cheatsheet',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='cheatsheet',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
