# Generated by Django 4.1.3 on 2022-12-31 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cheatsheet_num_vote_down_cheatsheet_num_vote_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatsheet',
            name='score',
        ),
    ]
